### ISSUE TITLE
How to decrease the required CUDA Memory in MonoGS

### ISSUE THREAD

**Issue by LeonGoretzkatju** [muskie82/MonoGS#31]
Hello,

Thank you so much for releasing this fantastic work! My computer has one RTX 4080 GPU with 16GB memory, when trying to run the system on realsense mode, it has the following error,
![Screenshot from 2024-03-20 21-48-38](https://github.com/muskie82/MonoGS/assets/53984646/2b896303-e9d1-41e6-9c70-b7a39d9b542b)
RuntimeError: CUDA out of memory. Tried to allocate 35.27 GiB (GPU 0; 15.69 GiB total capacity; 47.88 MiB already allocated; 10.16 GiB free; 60.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
So I was wondering which parameter I can adjust to make the required CUDA memory no more than my GPU volume in .yaml configuration file, Thank you!

**Comment by rmurai0610** [comment]
Hi, can you provide us with some more details?
Does the system work with the standard dataset (e.g. on mono/fr3)?
Also, does this error come up as soon as the system starts?
It's weird that 35GiB is attempted to be allocated, and we've not seen this before.

**Comment by LeonGoretzkatju** [comment]
Thank you so much for your reply! The running message of testing MonoGS at fr3_office scene is shown as follows,
`(MonoGS) alex@alex-System-Product-Name:~/research/MonoGS$ python slam.py --config configs/mono/tum/fr3_office.yaml
MonoGS: saving results in results/datasets_tum/2024-03-21-16-23-56
FEngine (64 bits) created at 0x5268c7d0 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
Process Process-3:
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/research/MonoGS/utils/slam_backend.py", line 406, in run
    self.initialize_map(cur_frame_idx, viewpoint)
  File "/home/alex/research/MonoGS/utils/slam_backend.py", line 116, in initialize_map
    self.gaussians.max_radii2D[visibility_filter],
RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from stream_synchronize at /opt/conda/conda-bld/pytorch_1659484801627/work/c10/cuda/CUDAFunctions.h:85 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f934344e497 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x62c87b (0x7f938344887b in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x46e578 (0x7f938328a578 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: c10::TensorImpl::release_resources() + 0x175 (0x7f9343431d95 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x35fb45 (0x7f938317bb45 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6b03e0 (0x7f93834cc3e0 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x308 (0x7f93834cc7e8 in /home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4ad077]
frame #8: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4d7524]
frame #9: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4d58c8]
frame #10: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4ad077]
frame #11: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4d7524]
frame #12: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x4a0cf7]
frame #13: _PyModule_ClearDict + 0x10c (0x526aac in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #14: PyImport_Cleanup + 0x2c3 (0x5776c3 in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #15: Py_FinalizeEx + 0x67 (0x572c97 in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #16: Py_Exit + 0x8 (0x57cf78 in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #17: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x57ca82]
frame #18: PyErr_PrintEx + 0x35 (0x573a15 in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #19: PyRun_SimpleStringFlags + 0x63 (0x569d53 in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #20: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x5490d7]
frame #21: _Py_UnixMain + 0x3c (0x548fec in /home/alex/miniconda3/envs/MonoGS/bin/python)
frame #22: __libc_start_main + 0xf3 (0x7f93bb3f1083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #23: /home/alex/miniconda3/envs/MonoGS/bin/python() [0x548e9e]`
![Screenshot from 2024-03-21 16-24-34](https://github.com/muskie82/MonoGS/assets/53984646/2e0d7ec7-56b5-4817-8836-80f1dfb00102)
Also, the GUI cannot show the RGB and depth images.
**CUDA out of memory** happened when I try to run MonoGS using realsense camera, it shows that the following images,
`(MonoGS) alex@alex-System-Product-Name:~/research/MonoGS$ python slam.py --config configs/live/realsense.yaml
FEngine (64 bits) created at 0x54476640 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
Process Process-3:
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/research/MonoGS/utils/slam_backend.py", line 406, in run
    self.initialize_map(cur_frame_idx, viewpoint)
  File "/home/alex/research/MonoGS/utils/slam_backend.py", line 90, in initialize_map
    viewpoint, self.gaussians, self.pipeline_params, self.background
  File "/home/alex/research/MonoGS/gaussian_splatting/gaussian_renderer/__init__.py", line 140, in render
    rho=viewpoint_camera.cam_trans_delta,
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 243, in forward
    raster_settings,
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 45, in rasterize_gaussians
    raster_settings,
  File "/home/alex/miniconda3/envs/MonoGS/lib/python3.7/site-packages/diff_gaussian_rasterization/__init__.py", line 99, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer, depth, opacity, n_touched = _C.rasterize_gaussians(*args)
RuntimeError: CUDA out of memory. Tried to allocate 35.23 GiB (GPU 0; 15.69 GiB total capacity; 47.88 MiB already allocated; 9.44 GiB free; 60.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
Also, in Realsense mode, it still cannot show images on GUI, and the CUDA error happened after resetting the system.
Thank you!

**Comment by rmurai0610** [comment]
I think there is something wrong with cuda (possibly installation)
Can you run the python command but like `CUDA_LAUNCH_BLOCKING=1 python slam.py --config configs/mono/tum/fr3_office.yaml`?

Also, does original 3D Gaussian Splatting work for your machine?

**Comment by LeonGoretzkatju** [comment]
> I think there is something wrong with cuda (possibly installation) Can you run the python command but like `CUDA_LAUNCH_BLOCKING=1 python slam.py --config configs/mono/tum/fr3_office.yaml`?
> 
> Also, does original 3D Gaussian Splatting work for your machine?

Thank you for your guidance! I have solved this problem by running a docker in my computer, you can close this problem, Thank you!

**Comment by muskie82** [comment]
Thank you for letting us know.
Windows + Pytorch multiprocess seems problematic!
